- key:               mrja
  name:              Ganjacoin 
  client:            ganjacoin                             # API client name.
  server:            http://user:password@127.0.0.1:12310    # Public Ganjacoin node endpoint.
  height:            1087160                                 # Initial block number from which sync will be started.
  min_confirmations: 6                                       # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://www.explorer.ganjacoinpro.com/address/#{address}
    transaction:     https://www.explorer.ganjacoinpro.com/tx/#{txid}
  status:            active
